Update patch set 1
Patch Set 1:

Build failed, you have conflicts:
error: could not apply b1a62e9... [FAB-10576]: Check if puller got valid pvt rwset
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Build step 'Execute shell' marked build as failure

Patch-set: 1
Reviewer: Gerrit User 1000013 <1000013@391e9dfb-4ca7-4d02-9d3e-c661eec85686>
Label: Code-Review=0